<?php
/*
    This file is part of the Discope property management software <https://github.com/discope-pms/discope>
    Some Rights Reserved, Discope PMS, 2020-2025
    Original author(s): Yesbabylon SRL
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

use documents\Document;
use documents\DocumentTemp;
use documents\export\ExportingTask;
use equal\text\TextTransformer;

[$params, $providers] = eQual::announce([
    'description'   => "Proposes a downloadable ZIP document that contains all documents generated by given exporting task.",
    'params'        => [

        'id' =>  [
            'type'              => 'many2one',
            'description'       => "The assembly the invitation refers to.",
            'foreign_object'    => 'documents\export\ExportingTask',
            'required'          => true
        ]

    ],
    'response'      => [
        'content-type'  => 'application/zip',
        'charset'       => 'utf-8',
        'accept-origin' => '*'
    ],
    'providers'     => ['context']
]);

/**
 * @var \equal\php\Context  $context
 */
['context' => $context] = $providers;

$exportingTask = ExportingTask::id($params['id'])
    ->read([
        'status',
        'name',
        'is_temp',
        'exporting_task_lines_ids' => [
            'status',
            'document_id',
            'document_temp_id'
        ]
    ])
    ->first();

if(!$exportingTask) {
    throw new Exception("unknown_exporting_task", EQ_ERROR_UNKNOWN_OBJECT);
}

if($exportingTask['status'] !== 'ready') {
    throw new Exception("non_ready_exporting_task", EQ_ERROR_UNKNOWN_OBJECT);
}

// generate the zip archive
$tmp_file = tempnam(sys_get_temp_dir(), 'zip');
$zip = new ZipArchive();
if($zip->open($tmp_file, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
    // could not create the ZIP archive
    throw new Exception("Unable to create a ZIP file.", EQ_ERROR_UNKNOWN);
}

/** @var Document $document_class */
$document_class = Document::getType();
$document_id_column = 'document_id';
if($exportingTask['is_temp']) {
    $document_class = DocumentTemp::getType();
    $document_id_column = 'document_temp_id';
}

foreach($exportingTask['exporting_task_lines_ids'] as $exporting_task_line_id => $exportingTaskLine) {
    if($exportingTaskLine['status'] !== 'ready') {
        continue;
    }

    $document = $document_class::id($exportingTaskLine[$document_id_column])
        ->read(['name', 'data'])
        ->first();

    $zip->addFromString($document['name'], $document['data']);
}

$zip->close();

// read raw data
$data = file_get_contents($tmp_file);
unlink($tmp_file);

$max_length = 128;
$export_name = substr(str_replace(' ', '_', TextTransformer::normalize($exportingTask['name'])), 0, $max_length);

ExportingTask::id($params['id'])->update(['is_exported' => true]);

$context->httpResponse()
        ->header('Content-Disposition', 'attachment; filename="' . $export_name . '.zip"')
        ->body($data, true)
        ->send();
