version: 2.1

# Define the jobs we want to run for this project.
# We always test 2 previous PHP versions.
jobs:
  php_7-4:
    docker:
    - image: php:7.4-apache
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: equal
    working_directory: ~/repo
    steps:
      # install PHP dependencies
      - run: apt-get update && apt-get -y install git libzip-dev
      - run: docker-php-ext-install pdo pdo_mysql mysqli zip
      - run: docker-php-ext-enable mysqli
      # install equal
      - run:
          name: Clone equal (#todo - use dockerhub image)
          command: |
            git clone https://github.com/equalframework/equal.git ~/repo
            git checkout dev-2.0
            mv ~/repo/packages ~/repo/packages.core
      - checkout:
          path: ~/repo/packages
      - run:
          name: Copy core package
          command: |
            cp -r ~/repo/packages.core/core ~/repo/packages/
      # assign folders permissions
      - run: php run.php --do=init_fs
      # check that mandatory directories are present and have correct access rights set
      - run: php run.php --do=test_fs-consistency
      # check ability to connect to the dbms service
      - run: php run.php --do=test_db-connectivity
      # create an empty database
      - run: php run.php --do=init_db
      # initialize database with demo data
      - run: php run.php --do=init_package --package=discope
      # run test units
      - run: php run.php --do=test_package --package=core
      - run: php run.php --do=test_package --package=discope
      # export logs on failure
      - run:
          command: |
            mkdir -p /tmp/dumps
            cp ~/repo/log/equal.log /tmp/dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/dumps
  php_8-3:
    docker:
    - image: php:8.3-apache
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: equal
    working_directory: ~/repo
    steps:
      # install PHP dependencies
      - run: apt-get update && apt-get -y install git libzip-dev
      - run: docker-php-ext-install pdo pdo_mysql mysqli zip
      - run: docker-php-ext-enable mysqli
      # install equal
      - run:
          name: Clone equal (#todo - use dockerhub image)
          command: |
            git clone https://github.com/equalframework/equal.git ~/repo
            git checkout dev-2.0
            mv ~/repo/packages ~/repo/packages.core
      - checkout:
          path: ~/repo/packages
      - run:
          name: Copy core package
          command: |
            cp -r ~/repo/packages.core/core ~/repo/packages/
      # assign folders permissions
      - run: php run.php --do=init_fs
      # check that mandatory directories are present and have correct access rights set
      - run: php run.php --do=test_fs-consistency
      # check ability to connect to the dbms service
      - run: php run.php --do=test_db-connectivity
      # create an empty database
      - run: php run.php --do=init_db
      # initialize database with demo data
      - run: php run.php --do=init_package --package=discope
      # run test units
      - run: php run.php --do=test_package --package=core
      # export logs on failure
      - run:
          command: |
            mkdir -p /tmp/dumps
            cp ~/repo/log/equal.log /tmp/dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/dumps

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - php_7-4
      - php_8-3
